[package]
name = "semaforo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.100"
gpui = "0.2.2"
gpui-component = "0.3.1"
rust-embed = { version = "8.8.0", features = ["interpolate-folder-path"] }
